name: SSC
favicon: null
layout_spectrum: 0.7437276
typography_spectrum: 0.40805
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.1469534
  lightness: 0.7329749
  saturation: 0.9462366
  rhythmicContrast: 0.5217689
purpose: []
